### PR TITLE
fix(billing): show correct tier for declined payment statuses

### LINKED ISSUE #4447: Fix billing tier display for declined payments
When a user's payment declines, the UI currently shows that the user is on the Free tier. This is incorrect.

Users who are on a paid/billing tier should continue to be shown as on that billing tier while payment retries are in progress. The Free tier label should only be shown if the user is actually on the Free tier.

### PR DESCRIPTION
**Pull request by Ridhim-RR**
## What does this PR do?
Closes #4447

 When a user's payment declines, the UI incorrectly shows the user as on the Free tier. Users on a paid/billing tier should continue to see their
  billing tier while payment retries are in progress. The Free tier label should only be shown if the user is actually on the Free tier.

Fixes # (issue)
Updated the billing tier detection logic to treat  payment statuses (past_due) as paid subscriptions for UI purposes:
  1. Updated isFreeTier logic to use hasPaidSubscription instead of checking subscription status directly:

_If there is not an issue for this, please create one first. This is used to tracking purposes and also helps us understand why this PR exists_

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] Enhancement (small improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How should this be tested?

- Test A
- Test B

### Required

- [ ] Filled out the "How to test" section in this PR
- [x] Read [Contributing Guide](./CONTRIBUTING.md)
- [x] Self-reviewed my own code
- [x] Commented on my code in hard-to-understand areas
- [x] Ran `pnpm build`
- [x]  Ran `pnpm fmt`
- [ ] Ran `make fmt` on `/go` directory
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Unkey Docs if changes were necessary

### CODE REVIEW

**Comment by Flo4604** [comment]
@Ridhim-RR could you please sign the CLA

File: apps/dashboard/app/(app)/[workspaceSlug]/settings/billing/client.tsx [hunk 1]
```diff
@@ -70,7 +70,11 @@ export const Client: React.FC = () => {
 
   const allowUpdate = subscription && ["active", "trialing"].includes(subscription.status);
 
-  const isFreeTier = !subscription || !["active", "trialing"].includes(subscription.status);
+  const hasPaidSubscription = Boolean(
```
Comment (perkinsjr) [inline apps/dashboard/app/(app)/[workspaceSlug]/settings/billing/client.tsx:73]: This doesn't work as you expect. 

Currently your check will look for

"Subscription" and status of paid_due versus checking for active, trialing or past_due.

**Review by perkinsjr — CHANGES_REQUESTED** [review]
Please seem comments on your logical checks.
