### PR TITLE
fix: making pnpm local command to exit if db migration fails

### LINKED ISSUE #2854: Running `pnpm local` returns Table `unkey.workspaces` doesn't exist.
### Preliminary Checks

- [x] I have reviewed the documentation: https://unkey.com/docs

- [x] I have searched for existing issues: https://github.com/unkeyed/unkey/issues

- [x] This issue is not a question, general help request, or anything other than a bug report directly related to Unkey. Please ask questions in our Discord community: https://unkey.com/discord.

### Reproduction / Replay Link (Optional)

_No response_

### Issue Summary

I was trying to setup unkey locally following this doc: https://www.unkey.com/docs/contributing/getting-started. When I run `pnpm local`. I get 

```txt
 Setting up Unkey locally...
│
◇  What would you like to develop?
│  Dashboard
│
◇  services ready
│
◇  connected to database
│
◇  table migration complete
│
◇  Table 'unkey.workspaces' doesn't exist
```

### Steps to Reproduce

1. Clone the repository
2. Run `pnpm install`
3. Run `pnpm local`

### Expected behavior

Expected the app to run

### Other information

_No response_

### Screenshots

_No response_

### Version info

```markdown
- OS: MacOS
- Node: v23.5.0
- npm: 11.0.0
```

### PR DESCRIPTION
**Pull request by Nelwhix**
## What does this PR do?
This PR makes the `pnpm local` command exit if the database migrations are unsuccessful

Fixes #2854 (issue)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] Enhancement (small improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How should this be tested?
I found it really tricky to mimic the mysql disk is full message. so what I just did is make the migration fail by adding:
```ts
 plan: mysqlEnum("plan", ["free", "pro", "enterprise"]).default("invalid_value"),
```
on line 40 of https://github.com/unkeyed/unkey/blob/main/internal/db/src/schema/workspaces.ts

After doing this, run `pnpm local` and the command should fail at the migration step. before it would fail at the seed step without saying what went wrong

### Required

- [x] Filled out the "How to test" section in this PR
- [x] Read [Contributing Guide](./CONTRIBUTING.md)
- [x] Self-reviewed my own code
- [x] Commented on my code in hard-to-understand areas
- [x] Ran `pnpm build`
- [x] Ran `pnpm fmt`
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Unkey Docs if changes were necessary

## Summary by CodeRabbit

- **New Features**
  - Updated the MySQL container configuration to enforce a storage limit of 760MB.
- **Bug Fixes**
  - Enhanced error reporting during database migrations to deliver clearer feedback when issues occur.

### CODE REVIEW

File: tools/local/src/db.ts [hunk 1]
```diff
@@ -23,16 +23,25 @@ export async function prepareDatabase(url?: string): Promise<{
...
         cwd,
       });
+
+      p.stdout?.on("data", (data) => {
+        stdoutData += data;
+      });
+
       p.on("exit", (code) => {
         if (code === 0) {
+          if (stdoutData.includes("Error")) {
```
Comment (Nelwhix) [inline tools/local/src/db.ts:41]: stderr is empty and the exit code does not show failure. so I am scanning stdout for a migration failed message

**Review by chronark — APPROVED** [review]
