### PR TITLE
Fix/update validation issues status label

### LINKED ISSUE #4474: Tweak API key status summary to sound less alarming
When a significant portion of API requests are invalid (e.g. rate limited or missing permissions), the API key status currently shows the label "Potential issues" in the dashboard. This made it seem like something was broken even though the system was working as expected.

Update the status summary / label copy so that it more clearly communicates that many recent requests were invalid, without implying that the API or key itself is broken.

Relevant screenshot:

### PR DESCRIPTION
**Pull request by theabhayprajapati**
## What does this PR do?

Updated the API key status label for high error rates to communicate more clearly that the key is receiving invalid requests, rather than implying the API or key itself is broken.

**Changes:**
- Label: "Potential issues" → "High Error Rate"
- Tooltip: Updated to clarify that requests are invalid (rate limited, unauthorized, etc.) rather than suggesting system issues

**Why:** The previous label made it seem like something was broken with the API or key. The new label accurately reflects that the key is functioning correctly but receiving many invalid requests (which is expected behavior).

Fixes #4474

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] Enhancement (small improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How should this be tested?

**Code Review:**
- Verify the label text changed from "Potential issues" to "High Error Rate" in [constants.tsx](cci:7://file:///Users/abhayprajapati/Documents/OP/unkey/apps/dashboard/app/%28app%29/%5BworkspaceSlug%5D/apis/%5BapiId%5D/keys/%5BkeyAuthId%5D/_components/components/table/components/status-cell/constants.tsx:0:0-0:0)
- Verify the tooltip message was updated to clarify invalid requests
- Confirm no logic changes were made (only display text)

**Visual Testing (in production/staging):**
1. Create an API key
2. Generate verification requests with >10% error rate
3. Navigate to APIs → Keys page
4. Verify the status badge shows "High Error Rate" instead of "Potential issues"
5. Hover over the badge to see the updated tooltip

### Required

- [x] Filled out the "How to test" section in this PR
- [x] Read [Contributing Guide](./CONTRIBUTING.md)
- [x] Self-reviewed my own code
- [x] Commented on my code in hard-to-understand areas
- [ ] Ran `pnpm build` _(TypeScript-only change, no build required)_
- [x] Ran `pnpm fmt`
- [ ] Ran `make fmt` on `/go` directory _(No Go code changes)_
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [ ] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Unkey Docs if changes were necessary

### CODE REVIEW

**Comment by mcstepp** [comment]
Thanks for the contribution! Can you sign the CLA?

**Comment by theabhayprajapati** [comment]
done

> Thanks for the contribution! Can you sign the CLA?

done

File: apps/dashboard/app/(app)/[workspaceSlug]/apis/[apiId]/keys/[keyAuthId]/_components/components/table/components/status-cell/constants.tsx [hunk 1]
```diff
@@ -53,10 +53,11 @@ export const STATUS_DEFINITIONS: Record<StatusType, StatusInfo> = {
   },
   "validation-issues": {
     type: "validation-issues",
-    label: "Potential issues",
+    label: "High Error Rate",
     color: "bg-warningA-3 text-warningA-11",
     icon: <ShieldKey iconSize="sm-regular" className="text-warning-11" />,
-    tooltip: "This key has a high error rate. Please check its logs to debug potential issues.",
+    tooltip:
+      "This key is receiving many invalid requests (rate limited, unauthorized, etc.). Check logs to understand usage patterns.",
```
Comment (mcstepp) [inline apps/dashboard/app/(app)/[workspaceSlug]/apis/[apiId]/keys/[keyAuthId]/_components/components/table/components/status-cell/constants.tsx]: Let's go with "Elevated Rejections" for the label

Tooltip: "This key is receiving many rejected requests (rate limited, missing permissions, etc.). Please check your logs for usage details." 

My rationale is that "error" and "invalid" still makes it seem like a system bug vs expected behavior. Rejections / rejected requests makes it clear that the system is working as normal, and the keys are getting rejection scenarios.

**Review by mcstepp — DISMISSED** [review]

File: apps/dashboard/app/(app)/[workspaceSlug]/apis/[apiId]/keys/[keyAuthId]/_components/components/table/components/status-cell/constants.tsx (hunk 1 above)
Comment (chronark) [reply apps/dashboard/app/(app)/[workspaceSlug]/apis/[apiId]/keys/[keyAuthId]/_components/components/table/components/status-cell/constants.tsx]: I agree

Comment (theabhayprajapati) [reply apps/dashboard/app/(app)/[workspaceSlug]/apis/[apiId]/keys/[keyAuthId]/_components/components/table/components/status-cell/constants.tsx]: sure

Comment (theabhayprajapati) [reply apps/dashboard/app/(app)/[workspaceSlug]/apis/[apiId]/keys/[keyAuthId]/_components/components/table/components/status-cell/constants.tsx]: > Let's go with "Elevated Rejections" for the label
> 
> Tooltip: "This key is receiving many rejected requests (rate limited, missing permissions, etc.). Please check your logs for usage details."
> 
> My rationale is that "error" and "invalid" still makes it seem like a system bug vs expected behavior. Rejections / rejected requests makes it clear that the system is working as normal, and the keys are getting rejection scenarios.

made these updates

Comment (chronark) [reply apps/dashboard/app/(app)/[workspaceSlug]/apis/[apiId]/keys/[keyAuthId]/_components/components/table/components/status-cell/constants.tsx]: thank you!

**Review by MichaelUnkey — APPROVED** [review]
