### PR TITLE
fix: ip logging in api

### LINKED ISSUE #3340: Consider stripping Amazon injected headers in GA/ALB
In the go API we should strip the following headers before sending them to clickhouse

`X-Forwarded-For`
`X-Forwarded-Port`
`X-Amzn-Trace-Id`,
`X-Forwarded-Proto`

### LINKED ISSUE #4818: Stop logging client IP port in API logs
API logs currently store the requester as `ip:port`. The port component should no longer be logged; only the IP address should be retained.

### PR DESCRIPTION
**Pull request by Flo4604**
## What does this PR do?

Fixes #3340
Fixes #4818

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] Enhancement (small improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How should this be tested?

Tests

### Required

- [X] Filled out the "How to test" section in this PR
- [X] Read [Contributing Guide](./CONTRIBUTING.md)
- [X] Self-reviewed my own code
- [X] Commented on my code in hard-to-understand areas
- [X] Ran `pnpm build`
- [X] Ran `pnpm fmt`
- [X] Ran `make fmt` on `/go` directory
- [X] Checked for warnings, there are none
- [X] Removed all `console.logs`
- [X] Merged the latest changes from main onto my branch with `git pull origin main`
- [X] My changes don't cause any responsiveness issues

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Unkey Docs if changes were necessary

### CODE REVIEW

File: pkg/zen/middleware_metrics.go [hunk 1]
```diff
@@ -64,23 +79,21 @@ func WithMetrics(eventBuffer EventBuffer, info InstanceInfo) Middleware {
 			if s.ShouldLogRequestToClickHouse() {
 				requestHeaders := []string{}
 				for k, vv := range s.r.Header {
-					if strings.ToLower(k) == "authorization" {
-						requestHeaders = append(requestHeaders, fmt.Sprintf("%s: %s", k, "[REDACTED]"))
+					lk := strings.ToLower(k)
```
Comment (Flo4604) [inline pkg/zen/middleware_metrics.go:82]: as we found out in our uid package sprintf isnt the fastest so I just replaced it while we're here since we do log quiteabit into ch
