### PR TITLE
fix: Replaced clear button with reset filters button

### LINKED ISSUE #2394: `Reset Filters` button on `/ratelimits/:id/logs` redirects to `/audit` page
### Preliminary Checks

- [X] I have reviewed the documentation: https://unkey.com/docs

- [X] I have searched for existing issues: https://github.com/unkeyed/unkey/issues

- [X] This issue is not a question, general help request, or anything other than a bug report directly related to Unkey. Please ask questions in our Discord community: https://unkey.com/discord.

### Reproduction / Replay Link (Optional)

_No response_

### Issue Summary

The `Reset Filters` button on the `/ratelimits/:id/logs` page incorrectly redirects users to the `/audit` page instead of resetting the filters on the current logs page.

### Steps to Reproduce

1. Navigate to the `/ratelimits/:id/logs` page.
2. Apply any filters to the logs (e.g., identifier, IP address) **that result in no data being returned.**
3. Click the `Reset Filters` button.
4. Observe the redirection to the `/audit` page instead of the expected behavior.

### Expected behavior

When the `Reset Filters` button is clicked, the user should remain on the `/ratelimits/:id/logs` page. All applied filters should be cleared, displaying the default log view without redirection to another page.

### Other information

_No response_

### Screenshots

image

### Version info

```markdown
- OS:
- Node:
- npm:
```

### PR DESCRIPTION
**Pull request by BadriVishalPadhy**
## What does this PR do?  

replaced Clear-button with reset-filters-button because the clear button function and reset-filters-button function is same .Also clear button was only clearing one item but now resets all.

Fixes #2394

*If there is not an issue for this, please create one first. This is used to tracking purposes and also helps use understand why this PR exists*

## Type of change

- [ x] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ x] Enhancement (small improvements)
- [x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ x] This change requires a documentation update

## How should this be tested?

- Test A
- Test B

### Required

- [x ] Filled out the "How to test" section in this PR
- [ x] Read [Contributing Guide](./CONTRIBUTING.md)
- [ x] Self-reviewed my own code
- [x ] Commented on my code in hard-to-understand areas
- [x ] Ran `pnpm build`
- [ x] Ran `pnpm fmt`
- [ x] Checked for warnings, there are none
- [ x] Removed all `console.logs`
- [ x] Merged the latest changes from main onto my branch with `git pull origin main`
- [ x] My changes don't cause any responsiveness issues

### Appreciated

https://github.com/user-attachments/assets/189c7bd6-4d2c-492b-b883-0a6e441dce28

- [x] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Unkey Docs if changes were necessary

## Summary by CodeRabbit

- **New Features**
	- Enhanced functionality of the Filters component for better clarity and usability.
- **Bug Fixes**
	- Removed the filter reset link when no logs are found, simplifying the user interface.
- **Improvements**
	- Streamlined the filter reset process and refined state management for a smoother user experience.

### CODE REVIEW

File: apps/dashboard/app/(app)/ratelimits/[namespaceId]/logs/filter.tsx [hunk 1]
```diff
@@ -109,11 +109,14 @@ export const Filters: React.FC = () => {
             className="flex items-center h-8 gap-2 bg-background-subtle"
             onClick={() => {
```
Comment (ogzhanolguncu) [inline apps/dashboard/app/(app)/ratelimits/[namespaceId]/logs/filter.tsx:110]: Let's wrap the whole content in startTransition instead of using an empty one. Also, the 'Clear Filters' function needs to handle 'after' and 'before' dates - they currently aren't being reset when clearing filters.

Comment (BadriVishalPadhy) [reply apps/dashboard/app/(app)/ratelimits/[namespaceId]/logs/filter.tsx:110]: ok shall i do the change ?

Comment (ogzhanolguncu) [reply apps/dashboard/app/(app)/ratelimits/[namespaceId]/logs/filter.tsx:110]: Yeah, go ahead.

**Comment by BadriVishalPadhy** [comment]
@ogzhanolguncu check

**Comment by BadriVishalPadhy** [comment]
@chronark

**Comment by ogzhanolguncu** [comment]
Looks and works great.

**Review by ogzhanolguncu — APPROVED** [review]
