### PR TITLE
fix: project frontline routes n+1

### LINKED ISSUE #5847: N+1 Query
Sentry Issue: [UNKEY-DASHBOARD-7C](https://unkey-fw.sentry.io/issues/7408293619/?referrer=github_integration)
|  |  |
| ------------- | --------------- |
| **Offending Spans** | db - select `projects`.`id`, `projects_frontlin...

### PR DESCRIPTION
**Pull request by mcstepp**
## What does this PR do?

Fixes the N+1 query regression on the projects page where `deploy.domain.list` fires a separate lateral join query per project. Also fixes the `listProjects` query which produced duplicate rows when a project had multiple frontline routes.

Fixes #5847 

**Changes:**

1. `web/apps/dashboard/lib/trpc/routers/deploy/domains/list.ts` — Replaced Drizzle relational `findFirst` + `with: { frontlineRoutes }` (which generated an expensive lateral join subquery) with a flat `SELECT ... FROM frontline_routes INNER JOIN projects` that hits the `project_id_idx` index directly.

2. `web/apps/dashboard/lib/trpc/routers/deploy/project/list.ts` — Replaced the unbounded `LEFT JOIN frontlineRoutes` (which multiplied rows per project when multiple routes existed) with a scalar subquery. The subquery prefers `live` sticky routes first, then falls back to most recently updated.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] Enhancement (small improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How should this be tested?

- Navigate to the projects list page (`/[workspaceSlug]/projects`) with multiple projects that have frontline routes. Verify:
  - Each project card displays a single domain (preferring the `live` sticky route, otherwise the most recently updated route)
  - No duplicate project cards appear
  - Network tab shows `deploy.domain.list` still returns correct data when navigating into a project
- Navigate into a project detail page. Verify:
  - Domains load correctly in the overview
  - Promotion and rollback dialogs still show correct domain lists
  - Domain ordering is by `updatedAt` descending
- Check Sentry/query logs: the lateral join SQL (`LEFT JOIN lateral (SELECT coalesce(json_arrayagg(...)))`) should no longer appear for `deploy.domain.list` calls. Instead you should see a simple `SELECT ... FROM frontline_routes INNER JOIN projects WHERE ...`
- Verify workspace isolation: a user should only see domains for projects in their own workspace

### Required

- [x] Filled out the "How to test" section in this PR
- [x] Read [Contributing Guide](./CONTRIBUTING.md)
- [x] Self-reviewed my own code
- [x] Commented on my code in hard-to-understand areas
- [x] Ran `pnpm build`
- [x] Ran `pnpm fmt`
- [ ] Ran `make fmt` on `/go` directory
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Unkey Docs if changes were necessary

### CODE REVIEW

File: web/apps/dashboard/app/(app)/[workspaceSlug]/projects/[projectId]/(overview)/navigations/project-navigation.tsx [hunk 1]
```diff
@@ -58,9 +58,7 @@ export const ProjectNavigation = ({ onMount }: ProjectNavigationProps) => {
 
   const [isRedeployOpen, setIsRedeployOpen] = useState(false);
   const targetDeploymentId = routeDeploymentId ?? currentDeploymentId ?? null;
-  const selectedDeployment = targetDeploymentId
-    ? getDeploymentById(targetDeploymentId)
-    : undefined;
+  const selectedDeployment = targetDeploymentId ? getDeploymentById(targetDeploymentId) : undefined;
```
Comment (mcstepp) [inline web/apps/dashboard/app/(app)/[workspaceSlug]/projects/[projectId]/(overview)/navigations/project-navigation.tsx:61]: fmt did this

File: web/apps/dashboard/lib/trpc/routers/deploy/domains/list.ts [hunk 2]
```diff
@@ -1,36 +1,37 @@
...
+        sticky: frontlineRoutes.sticky,
+        createdAt: frontlineRoutes.createdAt,
+        updatedAt: frontlineRoutes.updatedAt,
       })
+      .from(frontlineRoutes)
+      .innerJoin(
+        projects,
+        and(eq(projects.id, frontlineRoutes.projectId), eq(projects.workspaceId, ctx.workspace.id)),
+      )
+      .where(eq(frontlineRoutes.projectId, input.projectId))
```
Comment (chronark) [inline web/apps/dashboard/lib/trpc/routers/deploy/domains/list.ts]: I'm paranoid that we accept user input here without ANDing the `eq(frontlineRoutes.workspaceId, ctx.workspace.id)`

File: web/apps/dashboard/lib/trpc/routers/deploy/project/list.ts [hunk 3]
```diff
@@ -57,7 +57,13 @@ export const listProjects = workspaceProcedure
         ${deployments.gitCommitAuthorHandle},
         ${deployments.gitCommitAuthorAvatarUrl},
         ${deployments.gitCommitTimestamp},
-        ${frontlineRoutes.fullyQualifiedDomainName},
+        (
+          SELECT fr.fully_qualified_domain_name
+          FROM ${frontlineRoutes} fr
+          WHERE fr.project_id = ${projects.id}
```
Comment (chronark) [inline web/apps/dashboard/lib/trpc/routers/deploy/project/list.ts:64]: same here actually, we should probably be over cautious and just check for workspace id too

**Review by chronark — CHANGES_REQUESTED** [review]

File: web/apps/dashboard/lib/trpc/routers/deploy/domains/list.ts (hunk 2 above)
Comment (mcstepp) [reply web/apps/dashboard/lib/trpc/routers/deploy/domains/list.ts]: fixed

File: web/apps/dashboard/lib/trpc/routers/deploy/project/list.ts (hunk 3 above)
Comment (mcstepp) [reply web/apps/dashboard/lib/trpc/routers/deploy/project/list.ts:64]: fixed

**Review by Flo4604 — APPROVED** [review]

**Review by chronark — APPROVED** [review]
