### PR TITLE
fix: deleting identity shouldn't 500

### LINKED ISSUE #4102: Fix timing issue when deleting same identity in parallel
@flo said:

> I found it, its a timing issue when deleting the same identity in parallel

### PR DESCRIPTION
**Pull request by Flo4604**
## What does this PR do?

Fixes #4102 aka when you'd delete a identity we would sometimes 500 because we'd confuse which identity to hard delete and what to soft delete.

Improves the performance of finding an identity using a union query to either find id or external id as the OR was leading to a full table scan.

Splits up FindIdentity to FindIdentityByID and FindIdentityByExternalID for tests.

Selects ratelimits with the identity so we can skip the second query.

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [X] Enhancement (small improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How should this be tested?

Create identities via identities Api's, update them delete them in parallel and test around.

What didn't work was

Create Identity via API 
Delete identity 
Create Identity via API 
Delete again
Create Identity via API 
Try to delete -> we would 500 here. 

### Required

- [X] Filled out the "How to test" section in this PR
- [X] Read [Contributing Guide](./CONTRIBUTING.md)
- [X] Self-reviewed my own code
- [X] Commented on my code in hard-to-understand areas
- [X] Ran `pnpm build`
- [X] Ran `pnpm fmt`
- [X] Checked for warnings, there are none
- [X] Removed all `console.logs`
- [X] Merged the latest changes from main onto my branch with `git pull origin main`
- [X] My changes don't cause any responsiveness issues

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Unkey Docs if changes were necessary

### CODE REVIEW

File: go/apps/api/routes/v2_identities_get_identity/handler.go [hunk 1]
```diff
@@ -52,53 +51,34 @@ func (h *Handler) Handle(ctx context.Context, s *zen.Session) error {
...
 
-		return IdentityResult{Identity: identity, Ratelimits: ratelimits}, nil
-	})
-	if err != nil {
-		return err
+	// Parse ratelimits JSON
+	var ratelimits []db.RatelimitInfo
+	if ratelimitBytes, ok := identity.Ratelimits.([]byte); ok && ratelimitBytes != nil {
+		_ = json.Unmarshal(ratelimitBytes, &ratelimits) // Ignore error, default to empty array
 	}
```
[the remark this answers is not in the document]
Comment (Flo4604) [reply go/apps/api/routes/v2_identities_get_identity/handler.go:80]: Since we are selecting a JSON from the db I don't see how this would be a bad json object in the first place and it it is a byte value all the time.

File: go/pkg/db/queries/identity_find_with_ratelimits.sql [hunk 2]
```diff
@@ -0,0 +1,45 @@
...
+            JSON_OBJECT(
+                'id', rl.id,
+                'name', rl.name,
+                'key_id', rl.key_id,
+                'identity_id', rl.identity_id,
+                'limit', rl.`limit`,
+                'duration', rl.duration,
+                'auto_apply', rl.auto_apply = 1
+            )
+        )
```
[the remark this answers is not in the document]
Comment (Flo4604) [reply go/pkg/db/queries/identity_find_with_ratelimits.sql:15]: That is not true.

[the remark this answers is not in the document]
Comment (Flo4604) [reply go/pkg/db/queries/identity_find_with_ratelimits.sql:15]: yes

File: go/pkg/db/queries/identity_find_by_external_id.sql
Comment (ogzhanolguncu) [inline go/pkg/db/queries/identity_find_by_external_id.sql:1]: I thought we were doing query per file? Also file name is a bit hacky since this file now handles two queries.

**Review by ogzhanolguncu — APPROVED** [review]

File: go/apps/api/routes/v2_identities_update_identity/handler.go [hunk 3]
```diff
@@ -112,51 +112,47 @@ func (h *Handler) Handle(ctx context.Context, s *zen.Session) error {
...
-		if err != nil && !db.IsNotFound(err) {
-			// nolint:exhaustruct
-			return db.Identity{}, fault.Wrap(err,
-				fault.Internal("unable to fetch ratelimits"), fault.Public("We're unable to retrieve the identity's ratelimits."),
-			)
-		}
+	// Parse existing ratelimits from JSON
+	var existingRatelimits []db.RatelimitInfo
+	if ratelimitBytes, ok := identityRow.Ratelimits.([]byte); ok && ratelimitBytes != nil {
+		_ = json.Unmarshal(ratelimitBytes, &existingRatelimits) // Ignore error, default to empty array
```
Comment (imeyer) [inline go/apps/api/routes/v2_identities_update_identity/handler.go:141]: nit: Ignoring the error when we have a sane default is 👍🏼 but having a debug log here and incrementing an error metric would be nice to have to know if for whatever reason we just stop being able to unmarshal.

File: go/apps/api/routes/v2_identities_update_identity/handler.go [hunk 4]
```diff
@@ -165,10 +161,10 @@ func (h *Handler) Handle(ctx context.Context, s *zen.Session) error {
 				UserAgent:   s.UserAgent(),
 				Resources: []auditlog.AuditLogResource{
 					{
-						ID:          identity.ID,
+						ID:          identityRow.ID,
 						Type:        auditlog.IdentityResourceType,
-						Name:        identity.ExternalID,
-						DisplayName: identity.ExternalID,
+						Name:        identityRow.ExternalID,
```
Comment (imeyer) [inline go/apps/api/routes/v2_identities_update_identity/handler.go:166]: random: Why `Name` and `DisplayName` if they're the same value?

File: go/apps/api/routes/v2_identities_update_identity/handler.go (hunk 3 above)
Comment (Flo4604) [reply go/apps/api/routes/v2_identities_update_identity/handler.go:141]: I agree but I dont't think we have a metric for this atm

I'll create an issue for this

Comment (imeyer) [reply go/apps/api/routes/v2_identities_update_identity/handler.go:141]: I think I suggested this same thing to Oguzhan and I'm not sure if he implemented it... 

https://github.com/unkeyed/unkey/pull/4107#discussion_r2448471520

I need to follow up there still. 😄

Comment (Flo4604) [reply go/apps/api/routes/v2_identities_update_identity/handler.go:141]: :D yeah lets keep this out of this pr then ill make a ticket for it regardless, also this shouldn't ever error except if mysql decides to not send a correct json

File: go/apps/api/routes/v2_identities_update_identity/handler.go (hunk 4 above)
Comment (Flo4604) [reply go/apps/api/routes/v2_identities_update_identity/handler.go:166]: It is supposed to be a human readable name to display in the UI, but in 99% case we don't have that anyways. 

So we are just setting it to the same thing atm, but this will be dropped in the new audilog schema
