### PR TITLE
fix(dashboard): keep users logged in through Domain Connect callback

### LINKED ISSUE #5894: Investigate why domain connect requires logging in again
Domain connect is requiring users to log in again. This may be caused by an assumption that cookies can be reused across redirects when they are not available there.

### PR DESCRIPTION
**Pull request by perkinsjr**
## What does this PR do?

Users who clicked Connect on the custom-domain "Automatic setup available" card were being asked to log in again after approving the DNS changes at their provider. 

The Domain Connect protocol redirects the user from app.unkey.com → DNS provider's consent page → back to a URL we choose. We were sending them straight to the deep, authenticated path `https://app.unkey.com/{slug}/projects/{id}/settings`. That page sits behind proxy.ts's auth middleware, and the session cookie is `SameSite=Strict`. Browsers strip Strict cookies on top-level cross-site navigation, so the request from the DNS provider arrived without a session, the middleware treated the user as unauthenticated, and bounced them to `/auth/sign-in`. This is the same constraint that the GitHub install callback, Stripe checkout/portal returns, and the WorkOS SSO callback all already work around.

The fix follows the existing pattern rather than relaxing the global cookie policy. A new public callback at `/integrations/domain-connect/callback` is added to proxy.ts's publicPaths so the cross-site return navigation isn't gated on the session cookie. The page reads a `?to=<safe relative path>` query parameter, validates it with the existing `isSafeRedirectPath` allowlist (no open-redirect risk), and router.replaces into the authenticated settings page. That second navigation is same-site, so the Strict cookie rides along and the user stays logged in. The ctrl `AddCustomDomain` handler is updated to sign the new callback URL as the Domain Connect `redirect_uri` instead of pointing the DNS provider straight at the protected deep link.

Fixes #5894

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] Enhancement (small improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How should this be tested?

- Add a custom domain whose DNS is hosted on Cloudflare; click Connect; approve in Cloudflare; confirm the browser lands on the project settings page still authenticated (no /auth/sign-in round-trip).
- Repeat with a Vercel-hosted domain to cover the second supported provider.
- Hit `/integrations/domain-connect/callback` directly with no to query param — confirm the page renders the "Invalid callback target" empty state instead of redirecting.
- Hit the callback with a malicious to value (e.g. to=//evil.com, to=https://evil.com) — confirm isSafeRedirectPath rejects it and the empty state is shown (no open redirect).
- Hit the callback while logged out — confirm the page itself loads (it's public) and the subsequent router.replace into the authenticated settings page bounces to sign-in as expected.
- Inspect the signed Domain Connect URL produced by AddCustomDomain and confirm the `redirect_uri` parameter is
  `https://app.unkey.com/integrations/domain-connect/callback?to=%2F<slug>%2Fprojects%2F<id>%2Fsettings`

### Required

- [X] Filled out the "How to test" section in this PR
- [X] Read [Contributing Guide](./CONTRIBUTING.md)
- [X] Self-reviewed my own code
- [X] Commented on my code in hard-to-understand areas
- [X] Ran `pnpm build`
- [X] Ran `pnpm fmt`
- [X] Ran `make fmt` on `/go` directory
- [X] Checked for warnings, there are none
- [X] Removed all `console.logs`
- [X] Merged the latest changes from main onto my branch with `git pull origin main`
- [X] My changes don't cause any responsiveness issues

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Unkey Docs if changes were necessary

### CODE REVIEW

File: web/apps/dashboard/app/(app)/integrations/domain-connect/callback/layout.tsx [hunk 1]
```diff
@@ -0,0 +1,6 @@
+export const dynamic = "force-dynamic";
+export const revalidate = 0;
+
+export default function Layout({ children }: { children: React.ReactNode }) {
+  return children;
```
Comment (chronark) [inline web/apps/dashboard/app/(app)/integrations/domain-connect/callback/layout.tsx:5]: what's the idea behind this?

**Review by chronark — APPROVED** [review]

**Review by Flo4604 — APPROVED** [review]
