### PR TITLE
fix: upsert ratelimit override

### LINKED ISSUE #3627: V2 API: Creating a ratelimit override should be upserted.
Currently when creating a ratelimit override that already exists we throw a db error even tho we should just upsert it in the first place

### PR DESCRIPTION
**Pull request by Flo4604**
## What does this PR do?

Fixes #3627 and removes unnecessary column from db

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] Chore (refactoring code, technical debt, workflow improvements)
- [ ] Enhancement (small improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

Tests

### Required

- [ ] Filled out the "How to test" section in this PR
- [ ] Read [Contributing Guide](./CONTRIBUTING.md)
- [ ] Self-reviewed my own code
- [ ] Commented on my code in hard-to-understand areas
- [ ] Ran `pnpm build`
- [ ] Ran `pnpm fmt`
- [ ] Checked for warnings, there are none
- [ ] Removed all `console.logs`
- [ ] Merged the latest changes from main onto my branch with `git pull origin main`
- [ ] My changes don't cause any responsiveness issues

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Unkey Docs if changes were necessary

## Summary by CodeRabbit

* **New Features**
  * Rate limit overrides can now be updated in place when using the same identifier, ensuring the latest limit and duration values are applied without creating duplicate entries.

* **Bug Fixes**
  * Improved consistency when creating or updating rate limit overrides with wildcard identifiers, ensuring the override ID remains unchanged and values are updated as expected.

* **Tests**
  * Enhanced test coverage for creating and updating rate limit overrides, including scenarios with wildcard identifiers and duplicate creation attempts.

### CODE REVIEW

File: internal/db/src/schema/rbac.ts [hunk 1]
```diff
@@ -54,7 +54,6 @@ export const permissionsRelations = relations(permissions, ({ one, many }) => ({
 export const keysPermissions = mysqlTable(
   "keys_permissions",
   {
-    tempId: bigint("temp_id", { mode: "number" }).autoincrement().notNull(),
```
Comment (chronark) [inline internal/db/src/schema/rbac.ts]: What's the order of merging here?
We need to migrate the db first, right?

Generally when schema changes are involved, please be extra careful about shipping the least amount of changes, cause it's a pain to roll back larger changes if necessary

In this case the perfect PR would be just addressing the column, nothing else

Comment (Flo4604) [reply internal/db/src/schema/rbac.ts]: yeah true that would be less painful I can re-add the column in this pr and open another one. and I think in this case we'd have to deploy first then migrate the db.

Since we dont want drizzle to use it in some select when it doesnt exist anymore

**Comment by chronark** [comment]
yeah, see this is already not trivial 😄
let’s do it in a separate PR then

File: internal/db/src/schema/rbac.ts (hunk 1 above)
Comment (Flo4604) [reply internal/db/src/schema/rbac.ts]: undid the changes will re-open another pr later this week
