### PR TITLE
fix: resolve N+1 deploy.domain.list calls on project overview

### LINKED ISSUE #5806: Fix N+1 query associated with projects
Fix the N+1 query associated with projects.

Related Sentry issue: [7408293619](<https://unkey-fw.sentry.io/issues/7408293619/>)

### PR DESCRIPTION
**Pull request by mcstepp**
## What does this PR do?

Fixes the N+1 issue on `deploy.domain.list` where the tRPC endpoint was called multiple times in a single batched request on the project overview page.

**Root causes:**
1. The `useEffect` in `data-provider.tsx` called `collection.domains.utils.refetch()` on every mount when `currentDeploymentId` was truthy, duplicating the fetch already triggered by `useLiveQuery`. Now tracks the previous value via a ref and only refetches when the deployment ID actually changes.
2. The `frontline_routes` table was missing a `project_id` index. The lateral join in the Drizzle-generated query filters on `project_id` but had no index, causing a full table scan.

**Side quest:** Replaced `<button disabled aria-hidden="true">` elements with `<span>` in the active deployment card skeleton. Disabled buttons with `aria-hidden="true"` violate a11y rules (focusable elements must not be aria-hidden). Since these are decorative skeleton placeholders, `<span>` is the correct element.

Fixes #5806 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] Enhancement (small improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How should this be tested?

**N+1 fix:**
1. Open the project overview page (`/projects/[projectId]`) in the dashboard
2. Open browser DevTools → Network tab and filter by `trpc`
3. Verify that `deploy.domain.list` appears only once in the batched tRPC request on initial page load (previously appeared 4 times)
4. Navigate away and back to the project page — confirm still only 1 call
5. Trigger a promotion or rollback — confirm domains refetch correctly after the mutation completes and domain data displays correctly in the promotion/rollback dialogs

**a11y fix:**
1. Navigate to a project overview page while a deployment is loading (or throttle network in DevTools)
2. Verify the skeleton card renders correctly with "Requests", "Logs" text and chevron icon
3. Run Biome lint — confirm no `aria-hidden` on focusable element warnings

## ⚠️ Migration Required

This PR adds a `project_id` index to the `frontline_routes` table. After merging:

1. Run `make generate-sql` to regenerate `pkg/mysql/schema/frontline_routes.sql`
2. Apply the following to all database environments:

```sql
CREATE INDEX `project_id_idx` ON `frontline_routes` (`project_id`);
```

This is a non-blocking, additive index so its safe to apply without downtime.

### Required

- [x] Filled out the "How to test" section in this PR
- [x] Read [Contributing Guide](./CONTRIBUTING.md)
- [x] Self-reviewed my own code
- [x] Commented on my code in hard-to-understand areas
- [x] Ran `pnpm build`
- [x] Ran `pnpm fmt`
- [ ] Ran `make fmt` on `/go` directory
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Unkey Docs if changes were necessary

### CODE REVIEW

File: web/apps/dashboard/app/(app)/[workspaceSlug]/projects/[projectId]/components/active-deployment-card/components/skeleton.tsx [hunk 1]
```diff
@@ -55,19 +55,15 @@ export function ActiveDeploymentCardSkeleton() {
               <div className="h-2 w-24 bg-grayA-4 rounded-sm" />
             </div>
           </div>
-          <div className="flex items-center gap-1.5">
-            <button className="text-xs text-grayA-9" type="button" disabled aria-hidden="true">
-              Requests
-            </button>
+          <div className="flex items-center gap-1.5" aria-hidden="true">
+            <span className="text-xs text-grayA-9">Requests</span>
```
Comment (mcstepp) [inline web/apps/dashboard/app/(app)/[workspaceSlug]/projects/[projectId]/components/active-deployment-card/components/skeleton.tsx:59]: linter was screaming about hidden arias on disabled buttons, so I changed them to spans since they're non-interactive

**Review by chronark — APPROVED** [review]

**Review by Flo4604 — APPROVED** [review]
