### PR TITLE
fix: resolve pricing issues

### LINKED ISSUE #1508: Outdated pricing defaults
### Preliminary Checks

- [X] I have reviewed the documentation: https://unkey.dev/docs

- [X] I have searched for existing issues: https://github.com/unkeyed/unkey/issues

- [X] This issue is not a question, general help request, or anything other than a bug report directly related to Unkey. Please ask questions in our Discord community: https://unkey.dev/discord.

### Reproduction / Replay Link (Optional)

_No response_

### Issue Summary

There are 3 issues related to the latest pricing change:

1. The free plan max quota is still hard-capping 100 active keys as limit instead of 1k
2. In the Billing section, the plan features shown are outdated
3. New pro plans are created with an outdated verification pricing tier, which will result in not invoicing them according to the current pricing.

#### For the first issue:
1. In a free workspace try to create 101 api keys. Just override the tinybird stats for the free plan.
2. You will see that the max quota banner is shown. (The actual free pricing max quota for active keys is 1k).

#### For the second issue:
If you head to the Billing section in a workspace with a free/pro plan you will see the outdated features:
<div style="display:flex;">
image
image
</div>

#### For the third issue:
1. In a free workspace try to make 150k verifications. Just override the tinybird stats.
2. Run an invoicing job.
3. The invoice will create an additional charge because the current `workspace.subscriptions.verifications` has the first tier linked to 100k instead of 150k.

### Expected behavior

The expected behaviour is that all pricing reflects what is shown on the landing pricing page.

### Other information

_No response_

### Screenshots

_No response_

### Version info

```markdown
- OS: Atari TOS
- Node: v20.11.1
- npm: v10.2.4
```

### PR DESCRIPTION
**Pull request by ubinatus**
## What does this PR do?

Fixes #1508 

*If there is not an issue for this, please create one first. This is used to tracking purposes and also helps use understand why this PR exists*

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] Enhancement (small improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How should this be tested?

- Test A: Free plan max quota
In a new free workspace, set the current api keys to 101, the hard cap banner should no longer appear.
- Test B: Pro subscription invoicing
In a pro workspace, set the current verifications to 150k and generate an invoice. The user should not get charged an additional amount.

### Required

- [x] Filled out the "How to test" section in this PR
- [x] Read [Contributing Guide](./CONTRIBUTING.md)
- [x] Self-reviewed my own code
- [x] Commented on my code in hard-to-understand areas
- [x] Ran `pnpm build`
- [x] Ran `pnpm fmt`
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Unkey Docs if changes were necessary

### CODE REVIEW

File: apps/dashboard/app/(app)/settings/billing/page.tsx
Comment (ubinatus) [inline apps/dashboard/app/(app)/settings/billing/page.tsx:1]: `workspace.plan === "free"` will never resolve.

File: apps/dashboard/app/(app)/settings/billing/plans/page.tsx
Comment (ubinatus) [inline apps/dashboard/app/(app)/settings/billing/plans/page.tsx:1]: Updating here using the current /pricing from the landing as source.

File: internal/billing/src/quota.ts
Comment (ubinatus) [inline internal/billing/src/quota.ts:1]: `QUOTAS.pro` is not used in the codebase.

**Review by ubinatus — COMMENTED** [review]
RTR

File: apps/dashboard/app/(app)/settings/billing/page.tsx
Comment (chronark) [reply apps/dashboard/app/(app)/settings/billing/page.tsx:1]: why not?

File: apps/dashboard/app/(app)/settings/billing/plans/page.tsx [hunk 1]
```diff
@@ -12,35 +12,35 @@ const tiers = {
...
+      "90-day analytics retention",
+      "90-day audit log retention",
       "Unlimited APIs",
       "Workspaces with team members",
-      "90 Days Analytics Retention",
-      "90 Days Audit Log Retention",
     ],
     footnotes: [
       "*  Additional active keys are billed at $0.10",
-      "** Additional verifications are billed at $10 per 100,000",
```
Comment (chronark) [inline apps/dashboard/app/(app)/settings/billing/plans/page.tsx:43]: this was intentional, why do you propose changing it?

File: apps/dashboard/app/(app)/settings/billing/plans/page.tsx [hunk 2]
```diff
@@ -12,35 +12,35 @@ const tiers = {
...
+      "2.5M successful ratelimits / month ***",
+      "90-day analytics retention",
+      "90-day audit log retention",
       "Unlimited APIs",
       "Workspaces with team members",
-      "90 Days Analytics Retention",
-      "90 Days Audit Log Retention",
     ],
     footnotes: [
       "*  Additional active keys are billed at $0.10",
```
Comment (chronark) [inline apps/dashboard/app/(app)/settings/billing/plans/page.tsx:42]: 1mil+ keys will be a custom enterprise contact, there's no need for an asterisk here
```suggestion
   
```

File: apps/dashboard/app/(app)/settings/billing/plans/page.tsx [hunk 3]
```diff
@@ -12,35 +12,35 @@ const tiers = {
...
     href: "/app",
     price: 25,
-    description: "For those with teams and more demanding needs",
+    description: "For growing teams with powerful demands",
     buttonText: "Pro",
     features: [
-      "250 Monthly Active keys included *",
-      "150,000 Successful Verifications included **",
-      "2,500,000 Successful Ratelimits included ***",
+      "1M API keys *",
```
Comment (chronark) [inline apps/dashboard/app/(app)/settings/billing/plans/page.tsx:33]:
```suggestion
      "1M API keys",
```

File: apps/dashboard/app/(app)/settings/billing/page.tsx
Comment (ubinatus) [reply apps/dashboard/app/(app)/settings/billing/page.tsx:1]: Because `ProPlan` is rendered under the `workspace.plan !== "free"` condition:
https://github.com/unkeyed/unkey/blob/aebb009e8ebb3ca79b8769f6b929f6e59cc0215e/apps/dashboard/app/(app)/settings/billing/page.tsx#L39-L43

File: apps/dashboard/app/(app)/settings/billing/plans/page.tsx (hunk 1 above)
Comment (ubinatus) [reply apps/dashboard/app/(app)/settings/billing/plans/page.tsx:43]: Was following the same structure as the current landing /pricing features. Should this be reverted?

File: apps/dashboard/app/(app)/settings/billing/page.tsx
Comment (chronark) [reply apps/dashboard/app/(app)/settings/billing/page.tsx:1]: ah I see

File: apps/dashboard/app/(app)/settings/billing/plans/page.tsx [hunk 4]
```diff
@@ -12,36 +12,35 @@ const tiers = {
     name: "Free Tier",
     href: "/app",
     price: 0,
-    description: "Everything you need to start your next API!",
```
Comment (chronark) [inline apps/dashboard/app/(app)/settings/billing/plans/page.tsx:15]: This sounds like you can't use it in your existing API, let's revert

**Review by chronark — CHANGES_REQUESTED** [review]

File: apps/dashboard/app/(app)/settings/billing/plans/page.tsx (hunk 4 above)
Comment (chronark) [reply apps/dashboard/app/(app)/settings/billing/plans/page.tsx:15]: oh sorry, I'm dumb!

**Review by chronark — APPROVED** [review]
