### PR TITLE
fix(billing): add missing subscription fields and audit logging to upgrade flow

### LINKED ISSUE #2176: [billing] Missing subscription information during upgrade
### Preliminary Checks

- [X] I have reviewed the documentation: https://unkey.com/docs

- [X] I have searched for existing issues: https://github.com/unkeyed/unkey/issues

- [X] This issue is not a question, general help request, or anything other than a bug report directly related to Unkey. Please ask questions in our Discord community: https://unkey.com/discord.

### Reproduction / Replay Link (Optional)

_No response_

### Issue Summary

When a user initiates the upgrade to Pro, not all of the subscription is captured, disrupting user experience on the Pro Plan. 

### Steps to Reproduce

1. Log in a free workspace user with no stripe information
2. Initiate plan upgrade
3. Input stripe information and submit
4. Be redirected to dashboard, observe Pro labelling in dashboard
5. Observe db

### Expected behavior

DB should be populated with additional information

### Other information

side effect from #2120

### Screenshots

_No response_

### Version info

```markdown
- OS:
- Node:
- npm:
```

### PR DESCRIPTION
**Pull request by mcstepp**
## What does this PR do?

Additional subscription information was missing during upgrade. Adds audit logging also.

Fixes #2176 

*If there is not an issue for this, please create one first. This is used to tracking purposes and also helps use understand why this PR exists*

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] Enhancement (small improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How should this be tested?

Manual testing

1. Log in as free workspace user without stripe information
2. Initiate upgrade to pro
3. add stripe information and finish upgrade
4. Confirm upgrade in UI
5. Confirm subscription info in db
6. Confirm audit logs

### Required

- [x] Filled out the "How to test" section in this PR
- [x] Read [Contributing Guide](./CONTRIBUTING.md)
- [x] Self-reviewed my own code
- [x] Commented on my code in hard-to-understand areas
- [x] Ran `pnpm build`
- [x] Ran `pnpm fmt`
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Unkey Docs if changes were necessary

## Summary by CodeRabbit

- **New Features**
	- Enhanced subscription management with improved plan upgrade logic.
	- Integrated audit logging for tracking workspace updates during plan upgrades.
- **Bug Fixes**
	- Improved user authentication checks to ensure proper tenant ID and user existence validation.

### CODE REVIEW

File: apps/dashboard/app/(app)/settings/billing/stripe/success/page.tsx [hunk 1]
```diff
@@ -72,19 +76,64 @@ export default async function StripeSuccess(props: Props) {
...
+        ],
+        context: {
+          location: h.get("user-agent") ?? "unknown",
+          userAgent: h.get("x-forwarded-for") ?? process.env.VERCEL_REGION ?? undefined,
+        },
+      });
+    }
+  });
+
+  if (isUpgradingPlan) {
```
Comment (chronark) [inline apps/dashboard/app/(app)/settings/billing/stripe/success/page.tsx:136]: nit: we could just merge the two `if` clauses, right?

**Review by chronark — APPROVED** [review]

File: apps/dashboard/app/(app)/settings/billing/stripe/success/page.tsx (hunk 1 above)
Comment (mcstepp) [reply apps/dashboard/app/(app)/settings/billing/stripe/success/page.tsx:136]: I kept the PostHog call outside of the transaction call intentionally. If we want to merge the two if clauses, I can move the audit logging outside of the transaction too, but it looks like we wanted audit logging with the transaction. 

the two clauses are there for one within the transaction and one outside the transaction

File: apps/dashboard/app/(app)/settings/billing/stripe/success/page.tsx [hunk 2]
```diff
@@ -72,19 +76,64 @@ export default async function StripeSuccess(props: Props) {
...
+          {
+            type: "workspace",
+            id: ws.id,
+          },
+        ],
+        context: {
+          location: h.get("user-agent") ?? "unknown",
+          userAgent: h.get("x-forwarded-for") ?? process.env.VERCEL_REGION ?? undefined,
+        },
+      });
```
[the remark this answers is not in the document]
Comment (mcstepp) [reply apps/dashboard/app/(app)/settings/billing/stripe/success/page.tsx]: fixed

**Review by chronark — APPROVED** [review]
