### PR TITLE
Bug Fix: Improved full-width layout and text truncation to prevent overlap with button

### LINKED ISSUE #2348: Copy Icon Misalignment for Short Permission Names
### Preliminary Checks

- [X] I have reviewed the documentation: https://unkey.com/docs

- [X] I have searched for existing issues: https://github.com/unkeyed/unkey/issues

- [X] This issue is not a question, general help request, or anything other than a bug report directly related to Unkey. Please ask questions in our Discord community: https://unkey.com/discord.

### Reproduction / Replay Link (Optional)

_No response_

### Issue Summary

The copy icon for short permission names moves to the left, which is not intended. It should always stay on the right side of the permission name for consistent placement.

### Steps to Reproduce

1. Go to Dashboard.
2. Navigate to Authorization.
3. Click on Permissions.
4. Select any permission with a short name.
5. Observe the copy icon next to the permission name.
6. For short permission names, the copy icon shifts to the left.

### Expected behavior

The copy icon should remain on the right side of the permission name, maintaining consistent placement for all permission names.

### Other information

**Actual Behavior:** For short permission names, the copy icon shifts to the left.

### Screenshots

copy-button-spacing-when-permission-name-is-short

### Version info

```markdown
.
```

### PR DESCRIPTION
**Pull request by adityaraj-09**
## What does this PR do?

Added w-full to ensure the container takes the full width and added a max-w-[calc(100%-32px)] to the span containing permission.name to prevent it from overlapping with the button.

Fixes #2348

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] Enhancement (small improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How should this be tested?

Just go to Authorization/Permissions/ and then go to particular permission.

### Required

- [x] Filled out the "How to test" section in this PR
- [x] Read [Contributing Guide](./CONTRIBUTING.md)
- [x] Self-reviewed my own code
- [ ] Commented on my code in hard-to-understand areas
- [ ] Ran `pnpm build`
- [ ] Ran `pnpm fmt`
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Unkey Docs if changes were necessary

## Summary by CodeRabbit

- **New Features**
	- Improved layout and styling of the RolesPage component for better visual presentation of permissions.
	- Enhanced tooltip functionality for displaying permission names with a copy button.
	- Tooltip trigger area now occupies the full width of its container for better accessibility.

### CODE REVIEW

File: apps/dashboard/app/(app)/authorization/permissions/[permissionId]/page.tsx [hunk 1]
```diff
@@ -85,12 +85,12 @@ export default async function RolesPage(props: Props) {
...
             <Tooltip>
               <TooltipTrigger asChild>
-                <div className="flex items-center justify-between gap-2 truncate">
-                  <span className="truncate">{permission.name}</span>
-                  <div>
-                    <CopyButton value={permission.name} />
-                  </div>
-                </div>
+                 <div className="flex items-center justify-between gap-2 w-full truncate">
+        <span className="truncate max-w-[calc(100%-32px)]">{permission.name}</span>
```
Comment (chronark) [inline apps/dashboard/app/(app)/authorization/permissions/[permissionId]/page.tsx:89]: This is too brittle, if we now change the size of the copy button, this will break

a simple w-full might work

**Review by chronark — CHANGES_REQUESTED** [review]

**Comment by chronark** [comment]
please sign the CLA and fix the pr title

**Review by chronark — APPROVED** [review]
