### PR TITLE
fix(web): add ratelimit usage estimation

### LINKED ISSUE #1268: Missing ratelimits usage spending in `ProUsage`
### Preliminary Checks

- [X] I have reviewed the documentation: https://unkey.dev/docs

- [X] I have searched for existing issues: https://github.com/unkeyed/unkey/issues

- [X] This issue is not a question, general help request, or anything other than a bug report directly related to Unkey. Please ask questions in our Discord community: https://unkey.dev/discord.

### Reproduction / Replay Link (Optional)

_No response_

### Issue Summary

On the billing settings page, there seems to be missing the rate limits usage calculation on the `ProUsage` component.

### Steps to Reproduce

1. Consume the rate limit service.
2. Head to the settings section and the usage of ratelimit is not included in the current usage.

### Expected behavior

Include the Rate Limit service usage in the current usage estimation. The ratelimit usage should be retrieved using the `calculateTieredPrices` and added up into the `currentPrice` accumulator.

### Other information

_No response_

### Screenshots

_No response_

### Version info

```markdown
- OS: macOS 14.2.1
- Node: v20.11.1
- pnpm: v8.15.5
```

### PR DESCRIPTION
**Pull request by ubinatus**
## What does this PR do?

Fixes #1268 

*If there is not an issue for this, please create one first. This is used to tracking purposes and also helps use understand why this PR exists*

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] Enhancement (small improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Required

- [ ] Filled out the "How to test" section in this PR
- [x] Read [Contributing Guide](./CONTRIBUTING.md)
- [x] Self-reviewed my own code
- [x] Commented on my code in hard-to-understand areas
- [x] Ran `pnpm build`
- [x] Ran `pnpm fmt`
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Unkey Docs if changes were necessary

### CODE REVIEW

File: apps/web/app/(authenticated)/(app)/app/settings/billing/page.tsx [hunk 1]
```diff
@@ -250,6 +250,13 @@ const ProUsage: React.FC<{ workspace: Workspace }> = async ({ workspace }) => {
     currentPrice += cost.val.totalCentsEstimate;
     estimatedTotalPrice += forecastUsage(cost.val.totalCentsEstimate);
   }
+  if (workspace.subscriptions?.ratelimits) {
+    const cost = calculateTieredPrices(workspace.subscriptions.ratelimits.tiers, usedRatelimits);
+    if (cost.err) {
+      return <div className="text-red-500">{cost.err.message}</div>;
+    }
+    currentPrice += cost.val.totalCentsEstimate;
```
Comment (ubinatus) [inline apps/web/app/(authenticated)/(app)/app/settings/billing/page.tsx:258]: Should `forcastUsage` included here? It is also not included for the `activeKeys` service

Comment (chronark) [reply apps/web/app/(authenticated)/(app)/app/settings/billing/page.tsx:258]: yes it should, good catch

not for active keys though, as those don't necessarily scale with time

**Review by chronark — APPROVED** [review]

**Comment by chronark** [comment]
good catch
