### PR TITLE
fix: region not showing and wrong rl id

### LINKED ISSUE #3718: V2 API: Key Verification region is always empty
We need to write down the cloud region that accepted the request

### LINKED ISSUE #3720: V2: Key verify ratelimit array shows name instead of id
In the key verification response we show which ratelimits we checked and if they got exceeded or not.<br><br>When the ratelimit was auto applied and or requested without custom overrides we should show the actual ratelimit id instead of the name.

### PR DESCRIPTION
**Pull request by Flo4604**
## What does this PR do?

Fixes #3720
Fixes #3718

*If there is not an issue for this, please create one first. This is used to tracking purposes and also helps use understand why this PR exists*

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] Enhancement (small improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How should this be tested?

- Test A
- Test B

### Required

- [ ] Filled out the "How to test" section in this PR
- [ ] Read [Contributing Guide](./CONTRIBUTING.md)
- [ ] Self-reviewed my own code
- [ ] Commented on my code in hard-to-understand areas
- [ ] Ran `pnpm build`
- [ ] Ran `pnpm fmt`
- [ ] Checked for warnings, there are none
- [ ] Removed all `console.logs`
- [ ] Merged the latest changes from main onto my branch with `git pull origin main`
- [ ] My changes don't cause any responsiveness issues

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Unkey Docs if changes were necessary

## Summary by CodeRabbit

* **New Features**
  * Rate limit response data now includes a unique identifier for each rate limit, improving clarity in key verification responses.
  * Added geographic region information to key service configurations and telemetry events.

* **Style**
  * Improved code readability through reorganization and spacing adjustments in internal structures.

* **Chores**
  * Minor cleanup of extraneous blank lines in internal files.

### CODE REVIEW

File: go/internal/services/keys/verifier.go [hunk 1]
```diff
@@ -117,12 +125,12 @@ func (k *KeyVerifier) log() {
 		RequestID:   k.session.RequestID(),
 		WorkspaceID: k.Key.WorkspaceID,
 		Time:        time.Now().UnixMilli(),
-		Region:      "",
 		Outcome:     string(k.Status),
 		KeySpaceID:  k.Key.KeyAuthID,
 		KeyID:       k.Key.ID,
 		IdentityID:  k.Key.IdentityID.String,
 		Tags:        k.tags,
+		Region:      os.Getenv("UNKEY_REGION"),
```
Comment (chronark) [inline go/internal/services/keys/verifier.go]: It's a small thing, but can we pass this through from the cli args?

1. this might lead to inconsistent logs when the flag is provided via cli, rather than env
2. this might break easily if we rename the env variable, cause it's now used in two places

**Comment by Flo4604** [comment]
What do you think of having a globally available config so that we dont have to pass it down but can rather just access config.Region?

I can pass it down but then I have to embed it in each key verifier

**Comment by chronark** [comment]
not much tbh, that causes issues when running cluster tests.
it's slightly inconvenient to pass it down, but really not that bad imo

**Review by chronark — APPROVED** [review]
