### PR TITLE
fix: change table query to include deleted keys

### LINKED ISSUE #5842: Metrics chart totals do not match table counts
On `/key` in the last 12 hours view, the totals shown in the chart do not match the per-table counts. One example shown was \~16k invalid in the chart while the table showed \~8.8k for the highlighted key.

Relevant page: [API view](<https://app.unkey.com/steamsets/apis/api_4GNJVN3tPZ6xJD4rJZSqeVmUqCN8>)

### PR DESCRIPTION
**Pull request by mcstepp**
## What does this PR do?

The keys overview page chart totals (VALID/INVALID) did not match the sum of per-key counts in the table below it. The chart queries ClickHouse directly and includes all verification data — including data from deleted keys. The table, however, joined ClickHouse results against MySQL and silently dropped rows for keys that had been deleted, losing their valid/invalid counts from the visible totals.

This PR changes the table query to keep rows for deleted keys (with `key_details: null`) so their usage data remains visible and the table totals stay consistent with the chart. When name or identity filters are active, deleted keys are still excluded since they can't match those filters.

Fixes #5842 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] Enhancement (small improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Setup: create a key and generate traffic

1. Navigate to an API in the dashboard, create a test key
2. Run a few hundred verifications against that key (mix of valid and invalid — e.g. use the key normally, then hit rate limits or use an expired key)
3. Wait a minute for ClickHouse materialized views to catch up

### Reproduce the original bug (before this PR)

4. Go to the API's keys overview page (the page with the bar chart + table)
5. Note the VALID and INVALID totals in the chart header
6. Sum the Valid and Invalid columns across all table rows (check all pages if paginated)
7. On `main`, if any keys were deleted, the chart totals will be higher than the table sum

### Verify the fix

8. Delete the test key via the dashboard or API
9. Refresh the keys overview page
10. The deleted key should still appear in the table with its valid/invalid counts, showing "—" for Name and External ID
11. The chart header totals (VALID/INVALID) should now match the sum of all table rows
12. Clicking the deleted key row should still navigate (the link will have the key ID, though details won't load since the key is deleted)

### Verify filters still work correctly

13. Apply a Name filter (e.g. filter by a specific key name) — deleted keys should NOT appear (they have no name to match)
14. Apply an Identity filter — deleted keys should NOT appear
15. Remove all filters — deleted keys should reappear
16. Apply a Key ID filter matching the deleted key's ID — the deleted key should appear (Key ID filtering happens in ClickHouse, not MySQL)

### Required

- [x] Filled out the "How to test" section in this PR
- [x] Read [Contributing Guide](./CONTRIBUTING.md)
- [x] Self-reviewed my own code
- [x] Commented on my code in hard-to-understand areas
- [x] Ran `pnpm build`
- [x] Ran `pnpm fmt`
- [ ] Ran `make fmt` on `/go` directory
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Unkey Docs if changes were necessary

### CODE REVIEW

File: web/apps/dashboard/app/(app)/[workspaceSlug]/projects/[projectId]/(overview)/navigations/project-navigation.tsx [hunk 1]
```diff
@@ -58,9 +58,7 @@ export const ProjectNavigation = ({ onMount }: ProjectNavigationProps) => {
 
   const [isRedeployOpen, setIsRedeployOpen] = useState(false);
   const targetDeploymentId = routeDeploymentId ?? currentDeploymentId ?? null;
-  const selectedDeployment = targetDeploymentId
-    ? getDeploymentById(targetDeploymentId)
-    : undefined;
+  const selectedDeployment = targetDeploymentId ? getDeploymentById(targetDeploymentId) : undefined;
```
Comment (mcstepp) [inline web/apps/dashboard/app/(app)/[workspaceSlug]/projects/[projectId]/(overview)/navigations/project-navigation.tsx:61]: this was changed via `pnpm fmt`

**Review by MichaelUnkey — APPROVED** [review]

**Review by chronark — APPROVED** [review]
