### PR TITLE
fix(web): resolve overlapping banners

### LINKED ISSUE #1042: Banners overlap each other if multiple are displayed
### Preliminary Checks

- [X] I have reviewed the documentation: https://unkey.dev/docs

- [X] I have searched for existing issues: https://github.com/unkeyed/unkey/issues

- [X] This issue is not a question, general help request, or anything other than a bug report directly related to Unkey. Please ask questions in our Discord community: https://unkey.dev/discord.

### Reproduction / Replay Link (Optional)

_No response_

### Issue Summary

CleanShot 2024-02-26 at 10 11 23@2x

### Steps to Reproduce

1. (for example) Went to ...
2. Clicked on...
3. ...

### Expected behavior

They should be stacked 

### Other information

_No response_

### Screenshots

CleanShot 2024-02-26 at 10 11 23@2x

### Version info

```markdown
- OS:
- Node:
- npm:
```

### PR DESCRIPTION
**Pull request by ubinatus**
## What does this PR do?

Fixes #1042 

You can find the Loom preview [here](https://www.loom.com/share/665d0dc0794547a9a9d329e1a4526d04?sid=c16238a5-d0db-4c28-a726-09a7231dae7e). It should now handle the overlapping of banners whenever a new banner is added, removed or if it's height changes when the window is resized. PD:  it's not a perfect solution as it reorders the banners bottom fixed position as many times as the number of banners currently rendered.

This PR also resolves other non-reported issues:
1. Banners intended to persist were not working. Slight bug that mixed the behaviour between Banners with LS persist or with just RS.
2. The usage of `useLocalStorage` for the banners were causing hydration issues even the directive of `<Banner/>` was "use client". Solved it with the `initializeWithValue: false` arg option.

*If there is not an issue for this, please create one first. This is used to tracking purposes and also helps use understand why this PR exists*

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [x] Enhancement (small improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How should this be tested?

- **Test A: Handle overlapping banners**
1. Make sure you qualify for a `UsageBanner` (trial ending in 7 days, plan exceeded, etc).
2. Make the RateLimit or Audit banner popup (e.g. for the rate limit, delete the `ratelimit_ui` LS key and head to the RateLimit section)
3. You should see both banners properly displayed banner.
4. Before dismissing them, try resizing your window and verify that there are no overlapping banners (specially for long text banners such as the Audit one).

- **Test B: Make sure Banners with LS persistance are working property.** 
1. Delete the `ratelimit_ui` LS key (skip this step if there isn't one).
6. Head to the rate limit section and opt-in in case you haven't.
7. You should see the banner.
8. Try to dismiss it and reload the page. Test passes if the banner is not shown again unless you delete the mentioned LS key.

### Required

- [x] Filled out the "How to test" section in this PR
- [x] Read [Contributing Guide](./CONTRIBUTING.md)
- [x] Self-reviewed my own code
- [x] Commented on my code in hard-to-understand areas
- [x] Ran `pnpm build`
- [x] Ran `pnpm fmt`
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues

### Appreciated

- [x] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Unkey Docs if changes were necessary

### CODE REVIEW

File: apps/web/app/(authenticated)/(app)/app/banner.tsx [hunk 1]
```diff
@@ -9,18 +8,9 @@ import Link from "next/link";
...
-
-  const workspace = await db.query.workspaces.findFirst({
-    where: (table, { and, eq, isNull }) =>
-      and(eq(table.tenantId, tenantId), isNull(table.deletedAt)),
-    with: {
-      apis: {
-        where: (table, { isNull }) => isNull(table.deletedAt),
-      },
-    },
-  });
```
Comment (ubinatus) [inline apps/web/app/(authenticated)/(app)/app/banner.tsx:23]: This part is not necessary as the the parent already cast that query. Better to pass it as prop.

File: apps/web/components/banner.tsx [hunk 2]
```diff
@@ -26,17 +26,47 @@ export const Banner: React.FC<PropsWithChildren<Props>> = ({
...
+    onResize: ({ height }) => {
+      if (height !== bannerHeightRef.current) {
+        // Update Banners.
+        updateBannersBottomPosition();
+
+        // Set current banner height.
+        bannerHeightRef.current = height ?? 0;
+      }
+    },
+  });
```
Comment (ubinatus) [inline apps/web/components/banner.tsx:47]: Orders banners bottom fixed position on window resize AND whenever the banner has a height change.

File: apps/web/components/banner.tsx [hunk 3]
```diff
@@ -26,17 +26,47 @@ export const Banner: React.FC<PropsWithChildren<Props>> = ({
...
   if (!visible) {
     return null;
   }
+
   return (
-    <div className="fixed inset-x-0 bottom-0 z-50 pointer-events-none sm:flex sm:justify-center sm:px-6 sm:pb-5 lg:px-8">
+    <div
+      ref={bannerRef}
+      style={{ opacity: 0 }}
+      className="Unkey__Banner fixed inset-x-0 bottom-0 z-50 pointer-events-none sm:flex sm:justify-center sm:px-6 sm:mb-5 lg:px-8"
```
Comment (ubinatus) [inline apps/web/components/banner.tsx:65]: Necessary "sm:mb-5" instead of "sm:pb-5" so that the height is calculated without the spacing. Otherwise, complicates the calculation since it's a responsive class,

File: apps/web/components/banner.tsx [hunk 4]
```diff
@@ -52,3 +82,18 @@ export const Banner: React.FC<PropsWithChildren<Props>> = ({
...
+ */
+function updateBannersBottomPosition() {
+  const banners = document.getElementsByClassName("Unkey__Banner");
+
+  let yOffset = 0;
+
+  // Must iterate backwards.
+  for (let i = banners.length - 1; i >= 0; i--) {
+    banners[i].setAttribute("style", `bottom:${yOffset}px;`);
+    yOffset += banners[i].getBoundingClientRect().height + 6;
```
Comment (ubinatus) [inline apps/web/components/banner.tsx:97]: number 6 is the spacing between banners.

**Review by ubinatus — COMMENTED** [review]
RTR

File: apps/web/components/banner.tsx [hunk 5]
```diff
@@ -26,17 +26,47 @@ export const Banner: React.FC<PropsWithChildren<Props>> = ({
   variant,
   persistChoice,
 }) => {
-  const [visible, setVisible] = persistChoice
+  const bannerHeightRef = useRef<number>(0);
+  const bannerRef = useRef<HTMLDivElement>(null);
+
+  const [visible, setVisible] = !persistChoice
```
Comment (ubinatus) [inline apps/web/components/banner.tsx:32]: See the `persistChoice` to `!persistChoice` issue

File: apps/web/app/(authenticated)/(app)/app/banner.tsx (hunk 1 above)
Comment (chronark) [reply apps/web/app/(authenticated)/(app)/app/banner.tsx:23]: it would be fine as that's cached and doesn't impact the page negatively
