### PR TITLE
feat(clickhouse): add configurable request timeout and fix query

### LINKED ISSUE #4608: TRPCError: Something went wrong when fetching data from ClickHouse.
Sentry Issue: [UNKEY-DASHBOARD-2A](https://unkey-fw.sentry.io/issues/7183354106/?referrer=github_integration)

```
TRPCError: Something went wrong when fetching data from ClickHouse.
  File "@unkey/dashboard/./lib/trpc/routers/identity/latestVerification.ts", line 47, in identityLastVerificationTime
    throw new TRPCError({
...
(5 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by perkinsjr**
## What does this PR do?

- Add optional `requestTimeout` configuration parameter to ClickHouse client with 30s default
- Update dashboard ClickHouse instance to use 20s request timeout
- Optimize latestVerification query to use aggregated table (key_verifications_per_minute_v3) instead of raw events
- Convert verification timestamp to Unix milliseconds for consistency
- Support request timeout configuration in both single URL and split query/insert URL modes
- Improve query performance by querying pre-aggregated data instead of raw verification events

Fixes #4608 

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [X] Enhancement (small improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How should this be tested?

- Try loading an identity last used date. It should be much faster now
- 
### Required

- [X] Filled out the "How to test" section in this PR
- [ ] Read [Contributing Guide](./CONTRIBUTING.md)
- [X] Self-reviewed my own code
- [ ] Commented on my code in hard-to-understand areas
- [X] Ran `pnpm build`
- [X] Ran `pnpm fmt`
- [X] Ran `make fmt` on `/go` directory
- [X] Checked for warnings, there are none
- [X] Removed all `console.logs`
- [ ] Merged the latest changes from main onto my branch with `git pull origin main`
- [ ] My changes don't cause any responsiveness issues

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Unkey Docs if changes were necessary

### CODE REVIEW

File: web/apps/dashboard/lib/trpc/routers/identity/latestVerification.ts [hunk 1]
```diff
@@ -13,8 +13,8 @@ export const identityLastVerificationTime = workspaceProcedure
     try {
       const query = clickhouse.querier.query({
         query: `
-          SELECT maxOrNull(time) as last_used
-          FROM default.key_verifications_raw_v2
+          SELECT maxOrNull(toUnixTimestamp(time) * 1000) as last_used
```
Comment (chronark) [inline web/apps/dashboard/lib/trpc/routers/identity/latestVerification.ts:16]:
```suggestion
          SELECT maxOrNull(toUnixTimestamp64Milli(time)) as last_used
```

File: web/internal/clickhouse/src/index.ts [hunk 2]
```diff
@@ -96,11 +96,13 @@ export type ClickHouseConfig =
       url?: string;
       insertUrl?: never;
       queryUrl?: never;
+      requestTimeout?: number;
     }
   | {
       url?: never;
       insertUrl: string;
       queryUrl: string;
+      requestTimeout?: number;
```
Comment (chronark) [inline web/internal/clickhouse/src/index.ts]: nit: how would a user know the unit here?
add a comment or call it `requestTimeoutMs`

File: web/apps/dashboard/lib/trpc/routers/identity/latestVerification.ts (hunk 1 above)
Comment (perkinsjr) [reply web/apps/dashboard/lib/trpc/routers/identity/latestVerification.ts:16]: The code you provided doesn't work with the req, which is why I wrote the code as you see here.

 
ClickHouseError: A value of illegal type was provided as 1st argument 'value' to function 'toUnixTimestamp64Milli'. Expected: DateTime64, got: DateTime: In scope SELECT maxOrNull(toUnixTimestamp64Milli(time)) AS last_used FROM default.key_verifications_per_minute_v3 WHERE (workspace_id = 'ws_5T9RoZVovQKV2Ygm') AND (identity_id = 'id_5TABd75k7icEn5jV').

File: web/internal/clickhouse/src/index.ts (hunk 2 above)
Comment (perkinsjr) [reply web/internal/clickhouse/src/index.ts]: Fair pushing changes
