### PR TITLE
fix: verification table misalignment

### LINKED ISSUE #2064: Alignment issue in Verifications table
### Preliminary Checks

- [X] I have reviewed the documentation: https://unkey.com/docs

- [X] I have searched for existing issues: https://github.com/unkeyed/unkey/issues

- [X] This issue is not a question, general help request, or anything other than a bug report directly related to Unkey. Please ask questions in our Discord community: https://unkey.com/discord.

### Reproduction / Replay Link (Optional)

_No response_

### Issue Summary

There is a minor alignment issue in Verifications table which pretty easy to fix.

### Steps to Reproduce

1.  Go here: https://app.unkey.com/apis/[api]/keys/[keys]/[key]
2. See Verifications table last column.

### Expected behavior

Table header and values should be aligned.

### Other information

_No response_

### Screenshots

image

### Version info

```markdown
- OS: MacOS
- Node: v22.8.0
- npm: 10.8.2
```

### PR DESCRIPTION
**Pull request by ogzhanolguncu**
## What does this PR do?

Fixes #2064

*If there is not an issue for this, please create one first. This is used to tracking purposes and also helps use understand why this PR exists*

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] Enhancement (small improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How should this be tested?

- Check verification table last column and make sure it aligns with data

### Required

- [x] Filled out the "How to test" section in this PR
- [x] Read [Contributing Guide](./CONTRIBUTING.md)
- [x] Self-reviewed my own code
- [x] Commented on my code in hard-to-understand areas
- [x] Ran `pnpm build`
- [x] Ran `pnpm fmt`
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues

### Appreciated

- [x] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Unkey Docs if changes were necessary

Final result:
image

## Summary by CodeRabbit

- **User Interface Enhancements**
	- Improved visual spacing of the "Latest Verifications" header for better layout.
	- Adjusted padding in the verification table for a more consistent styling.

- **Code Improvements**
	- Enhanced readability and maintainability of the verification outcomes logic.
	- Streamlined conditional rendering for improved performance and clarity.

### CODE REVIEW

File: apps/dashboard/app/(app)/apis/[apiId]/keys/[keyAuthId]/[keyId]/page.tsx [hunk 1]
```diff
@@ -276,8 +276,10 @@ export default async function APIKeyDetailPage(props: {
             </EmptyPlaceholder.Description>
           </EmptyPlaceholder>
         )}
+        <h2 className="text-2xl font-semibold leading-none tracking-tight mt-8">
+          Latest Verifications
+        </h2>
```
Comment (chronark) [inline apps/dashboard/app/(app)/apis/[apiId]/keys/[keyAuthId]/[keyId]/page.tsx:281]: huh, why above the divider?

Comment (ogzhanolguncu) [reply apps/dashboard/app/(app)/apis/[apiId]/keys/[keyAuthId]/[keyId]/page.tsx:281]: Other way around looks bad IMO. 
image
Like this, but we can roll it back if you want.
