### PR TITLE
fix: Default Bytes should only allow numbers

### LINKED ISSUE #2359: Default bytes allows characters while only needing numbers
### Preliminary Checks

- [X] I have reviewed the documentation: https://unkey.com/docs

- [X] I have searched for existing issues: https://github.com/unkeyed/unkey/issues

- [X] This issue is not a question, general help request, or anything other than a bug report directly related to Unkey. Please ask questions in our Discord community: https://unkey.com/discord.

### Reproduction / Replay Link (Optional)

_No response_

### Issue Summary

The Default Bytes API option allows characters to be entered, which leads to `NaN` showing.

### Steps to Reproduce

1. Visit app.unkey.com
2. Choose an API -> go into settings
3. Input an `a` in the Default Bytes field and see it turn into nan

### Expected behavior

I would expect not to be allowed to input characters in a field that only allows numbers. 

### Other information

_No response_

### Screenshots

CleanShot 2024-10-12 at 21 05 50@2x

### Version info

```markdown
-
```

### PR DESCRIPTION
**Pull request by harshsbhat**
## What does this PR do?

It makes sure that the user cannot type in "non number"  characters for default bytes

Fixes #2359

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] Enhancement (small improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How should this be tested?

Test A:

Go to API settings -> enter a string as a default byte. It won't allow you to do so.

### Required

- [x] Filled out the "How to test" section in this PR
- [x] Read [Contributing Guide](./CONTRIBUTING.md)
- [x] Self-reviewed my own code
- [x] Commented on my code in hard-to-understand areas
- [x] Ran `pnpm build`
- [x] Ran `pnpm fmt`
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Unkey Docs if changes were necessary

## Summary by CodeRabbit

- **New Features**
	- Enhanced the DefaultBytes component to accept only numeric input for better validation.
	- Added a description emphasizing that the default byte size must be between 8 and 255.

- **Bug Fixes**
	- Updated input handling to ensure that the form state accurately reflects numeric values entered by the user.
  
- **Improvements**
	- Reformatted query conditions in the OverridePage component for improved readability without altering functionality.

### CODE REVIEW

File: apps/dashboard/app/(app)/apis/[apiId]/settings/default-bytes.tsx [hunk 1]
```diff
@@ -84,7 +84,7 @@ export const DefaultBytes: React.FC<Props> = ({ keyAuth }) => {
               render={({ field }) => (
                 <Input
                   className="max-w-sm"
-                  {...field}
```
Comment (perkinsjr) [inline apps/dashboard/app/(app)/apis/[apiId]/settings/default-bytes.tsx:87]: Removing this, means that the current saved bytes in the database is not displayed on load / refresh.

**Review by perkinsjr — CHANGES_REQUESTED** [review]

File: apps/dashboard/app/(app)/apis/[apiId]/settings/default-bytes.tsx (hunk 1 above)
Comment (harshsbhat) [reply apps/dashboard/app/(app)/apis/[apiId]/settings/default-bytes.tsx:87]: @perkinsjr Pushed!

Comment (harshsbhat) [reply apps/dashboard/app/(app)/apis/[apiId]/settings/default-bytes.tsx:87]: the only problem is this 

https://www.loom.com/share/63dc66f52d8b4725a8c6c6fd91f238d8?sid=ee72d670-fa76-4a43-95f3-7ba63d19f453

I won't say this is a problem/issue per say. But backspacing fully won't get rid of the 0

Comment (perkinsjr) [reply apps/dashboard/app/(app)/apis/[apiId]/settings/default-bytes.tsx:87]: You need to fix that at the same time. The field should be empty if the user wants to remove the entire field and type a new number in. It certainly should be be `0` when nothing is in the field.

**Review by perkinsjr — CHANGES_REQUESTED** [review]
see my last comment.

File: apps/dashboard/app/(app)/apis/[apiId]/settings/default-bytes.tsx (hunk 1 above)
Comment (harshsbhat) [reply apps/dashboard/app/(app)/apis/[apiId]/settings/default-bytes.tsx:87]: It's 0 when there is nothing in the field. That's not the problem. If you try to type something after making it 0. It goes like `016 ` rather than `16. ` I am probably not articulating that well enough.

Comment (perkinsjr) [reply apps/dashboard/app/(app)/apis/[apiId]/settings/default-bytes.tsx:87]: Both are a problem 

It shouldn't be `0` when there is nothing in the field because technically the byte size default is never 0 when you don't have a default, nor should it be`016` when typing

Comment (harshsbhat) [reply apps/dashboard/app/(app)/apis/[apiId]/settings/default-bytes.tsx:87]: `016` is the only problem here. If it is anything below 8 save button will be disabled.

**Comment by harshsbhat** [comment]
> see my last comment.
give me 2 seconds. I will fix & push this

**Comment by harshsbhat** [comment]
@perkinsjr using `type="number"` is going to keep that 0 at the start. Everything Is working fine now IMO. Please check

This will just make sure that `onChange={(e) => field.onChange(Number(e.target.value.replace(/\D/g, "")))}` the user cannot type a string AND not keep the 0 at the start too.

**Review by perkinsjr — APPROVED** [review]
