### PR TITLE
fix: throw conflict error for duplicate roles/permissions

### LINKED ISSUE #2853: Bug: Creating a permission / role returns wrong id when hitting duplicate key.
### Preliminary Checks

- [x] I have reviewed the documentation: https://unkey.com/docs

- [x] I have searched for existing issues: https://github.com/unkeyed/unkey/issues

- [x] This issue is not a question, general help request, or anything other than a bug report directly related to Unkey. Please ask questions in our Discord community: https://unkey.com/discord.

### Reproduction / Replay Link (Optional)

_No response_

### Issue Summary

When creating a role/permissions and hitting the duplicate key, the API will return a newly generated ID and not the one that's already in the db.

### Steps to Reproduce

1. Create Role via API 
2. Create the same role again 

See two different ids in the responses but only one role in the db.

### Expected behavior

To get the correct ID or the API To fail with PRECONDITION_FAILED duplicate key/role.

I think the second approach would be correct instead of just upserting the role.  

### Other information

_No response_

### Screenshots

_No response_

### Version info

```markdown
-
```

### PR DESCRIPTION
**Pull request by Flo4604**
## What does this PR do?

- Fixes #2853 
- fixes the http.ts errors being different to the open API schema 
- Adds the 412 status code description to the open API schema, which is used when failing with `PRECONDITION_FAILED`, which pannes in the createIdentity endpoint.
- Clears `apps/api/src/routes/v1_keys_ami.ts` which was not being used as its a duplicate of `apps/api/src/routes/v1_keys_whoami.ts`
- Adds docs for `PRECONDITION_FAILED`
- Changes duplicate key identities error from `PRECONDITION_FAILED` to `CONFLICT`

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] Chore (refactoring code, technical debt, workflow improvements)
- [ ] Enhancement (small improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How should this be tested?

Running the createPermission and createRole tests.

### Required

- [X] Filled out the "How to test" section in this PR
- [X] Read [Contributing Guide](./CONTRIBUTING.md)
- [X] Self-reviewed my own code
- [X] Commented on my code in hard-to-understand areas
- [X] Ran `pnpm build`
- [X] Ran `pnpm fmt`
- [X] Checked for warnings, there are none
- [X] Removed all `console.logs`
- [X] Merged the latest changes from main onto my branch with `git pull origin main`
- [X] My changes don't cause any responsiveness issues

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [X] Updated the Unkey Docs if changes were necessary

## Summary by CodeRabbit

- **Bug Fixes**
	- Standardized error responses for duplicate or conflicting entries across identities, permissions, roles, and namespaces. Responses now consistently return HTTP 409 (Conflict).
	- Corrected error messages for clarity regarding conflict scenarios.
- **New Features**
	- Introduced an additional error response for HTTP status code 412.
	- Added documentation for the "PRECONDITION_FAILED" error.
- **Tests**
	- Expanded test coverage to ensure consistent handling of conflict errors during duplicate submissions.
	- Added tests for handling duplicate permission and role creation attempts.
	- Removed tests that incorrectly allowed duplicate permission and role creation.
- **Chores**
	- Removed an obsolete key authentication endpoint to streamline API functionality.

### CODE REVIEW

File: go/pkg/error_code/unkey_database_not_unique.go [hunk 1]
```diff
@@ -10,8 +10,8 @@ func NewUnkeyDatabaseNotUniqueError(err error) UnkeyDatabaseNotUniqueError {
 			err,
 			SystemUnkey,
 			NamespaceKey,
-			"NOT_UNIQUE",
```
Comment (Flo4604) [inline go/pkg/error_code/unkey_database_not_unique.go:13]: Not sure if this should stay as NOT_UNIQUE, I thought it would be better if the error codes are the same everywhere

File: apps/api/src/pkg/errors/http.ts [hunk 2]
```diff
@@ -13,7 +13,7 @@ const ErrorCode = z.enum([
   "USAGE_EXCEEDED",
   "DISABLED",
   "NOT_FOUND",
-  "NOT_UNIQUE",
+  "CONFLICT",
```
Comment (Flo4604) [inline apps/api/src/pkg/errors/http.ts:16]: I adjusted it FROM NOT_UNIQUE to CONFLICT as this better fits the 409 status code.

File: apps/dashboard/lib/trpc/routers/ratelimit/createNamespace.ts [hunk 3]
```diff
@@ -67,14 +67,14 @@ export const createNamespace = t.procedure
       .catch((e) => {
         if (e instanceof DatabaseError && e.body.message.includes("desc = Duplicate entry")) {
           throw new TRPCError({
-            code: "PRECONDITION_FAILED",
+            code: "CONFLICT",
             message: "duplicate namespace name. Please use a unique name for each namespace.",
```
Comment (ogzhanolguncu) [inline apps/dashboard/lib/trpc/routers/ratelimit/createNamespace.ts:71]: Nit:
To cure my OCD can we convert  this to

```ts
{    
message: `A namespace with name "${input.name}" already exists in this workspace. Please choose a different name.`
}
```

File: apps/api/src/routes/v1_permissions_createPermission.ts [hunk 4]
```diff
@@ -78,15 +79,20 @@ export const registerV1PermissionsCreatePermission = (app: App) =>
...
-        .onDuplicateKeyUpdate({
-          set: {
-            name: req.name,
-            description: req.description,
-          },
+        .catch((e) => {
+          if (e instanceof DatabaseError && e.body.message.includes("Duplicate entry")) {
+            throw new UnkeyApiError({
+              code: "CONFLICT",
+              message: "Duplicate Permission",
```
Comment (ogzhanolguncu) [inline apps/api/src/routes/v1_permissions_createPermission.ts:91]: Can add a better message like this:

```ts
{message: `Permission with name "${permission.name}" already exists in this workspace`}
```

File: apps/api/src/pkg/errors/openapi_responses.ts [hunk 5]
```diff
@@ -46,6 +46,17 @@ export const openApiErrorResponses = {
       },
     },
   },
+  412: {
+    description:
+      "This response is sent when the request does not meet one or more preconditions required for fulfillment.",
```
Comment (ogzhanolguncu) [inline apps/api/src/pkg/errors/openapi_responses.ts:51]: Something a bit detailed might be good. 

Example:
```sh
 description:  "The requested operation cannot be completed because certain conditions were not met. This typically occurs when a required resource state or version check fails."
```

File: go/pkg/error_code/unkey_database_not_unique.go (hunk 1 above)
Comment (ogzhanolguncu) [reply go/pkg/error_code/unkey_database_not_unique.go:13]: I agree. I think it's safe to keep them same.

**Review by ogzhanolguncu — COMMENTED** [review]
Some nits, but it looks good

File: apps/api/src/routes/v1_permissions_createRole.ts [hunk 6]
```diff
@@ -82,12 +83,17 @@ export const registerV1PermissionsCreateRole = (app: App) =>
...
-        .onDuplicateKeyUpdate({
-          set: {
-            name: req.name,
-            description: req.description,
-          },
+        .catch((e) => {
+          if (e instanceof DatabaseError && e.body.message.includes("Duplicate entry")) {
+            throw new UnkeyApiError({
+              code: "CONFLICT",
+              message: "Duplicate Role",
```
Comment (ogzhanolguncu) [inline apps/api/src/routes/v1_permissions_createRole.ts:90]:
```ts   
{message: `Role with name "${role.name}" already exists in this workspace`}
```

File: go/pkg/error_code/unkey_database_not_unique.go (hunk 1 above)
Comment (Flo4604) [reply go/pkg/error_code/unkey_database_not_unique.go:13]: 🫡

File: apps/api/src/routes/v1_identities_createIdentity.ts [hunk 7]
```diff
@@ -201,7 +201,10 @@ export const registerV1IdentitiesCreateIdentity = (app: App) =>
               },
             ],
 
-            context: { location: c.get("location"), userAgent: c.get("userAgent") },
+            context: {
```
Comment (Flo4604) [inline apps/api/src/routes/v1_identities_createIdentity.ts:204]: idk why this got formatted

Comment (Flo4604) [inline apps/api/src/routes/v1_identities_createIdentity.ts:204]: idk why this got formatted

**Comment by Flo4604** [comment]
fixed, tests didn't pass since error message is different now.

I just remove the body check, since the status code is unique for this error.

**Review by ogzhanolguncu — APPROVED** [review]

File: apps/api/src/routes/v1_identities_createIdentity.error.test.ts [hunk 8]
```diff
@@ -62,13 +62,6 @@ describe("when identity exists already", () => {
...
 
-    expect(res.status).toEqual(412);
-    expect(res.body).toMatchObject({
-      error: {
-        code: "PRECONDITION_FAILED",
-        docs: "https://unkey.dev/docs/api-reference/errors/code/PRECONDITION_FAILED",
-        message: "Duplicate identity",
-      },
-    });
+    expect(res.status, `expected 409, received: ${JSON.stringify(res, null, 2)}`).toEqual(409);
```
Comment (chronark) [inline apps/api/src/routes/v1_identities_createIdentity.error.test.ts:65]: why is the body check gone?

File: apps/api/src/routes/v1_identities_updateIdentity.error.test.ts [hunk 9]
```diff
@@ -97,13 +97,6 @@ describe("updating ratelimits", () => {
       },
     );
 
-    expect(res.status).toEqual(412);
-    expect(res.body).toMatchObject({
```
Comment (chronark) [inline apps/api/src/routes/v1_identities_updateIdentity.error.test.ts:101]: why is the body check gone?

File: apps/api/src/routes/v1_permissions_createPermission.error.test.ts [hunk 10]
```diff
@@ -39,3 +40,38 @@ describe.each([
...
 });
+
+test("creating the same permission twice returns conflict", async (t) => {
+  const h = await IntegrationHarness.init(t);
+  const root = await h.createRootKey(["rbac.*.create_permission"]);
+
+  const name = randomUUID();
+  // The First request should succeed
+  // The Second request should fail
+  const expectedStatuses: Record<number, number> = {
```
Comment (chronark) [inline apps/api/src/routes/v1_permissions_createPermission.error.test.ts:51]: fair enough but I feel like just running the function twice without a loop would be much easier to understand
let's keep it as is though

**Review by chronark — CHANGES_REQUESTED** [review]

File: apps/api/src/routes/v1_permissions_createPermission.error.test.ts (hunk 10 above)
Comment (Flo4604) [reply apps/api/src/routes/v1_permissions_createPermission.error.test.ts:51]: I've added them back for clarity's sake

File: apps/api/src/routes/v1_identities_createIdentity.error.test.ts (hunk 8 above)
Comment (Flo4604) [reply apps/api/src/routes/v1_identities_createIdentity.error.test.ts:65]: Since the 409 status code was only used for both endpoints in a single place, I thought their uniqueness was enough to check the status code. 

I've added both checks back.
