### PR TITLE
feat: allow changing default branch + fix manual deployment

### LINKED ISSUE #5469: Default branch config ignored for environment selection
`app.default_branch` does not appear to be applied when selecting the deployment environment.

If a user has `app.default_branch=staging`, a deployment from the `staging` branch should go to the prod environment. This should work for both GitHub-triggered and manual deployments.

During testing, branches tagged as `main` and `staging` both failed.

### PR DESCRIPTION
**Pull request by Flo4604**
## What does this PR do?

Adds configurable production branch settings to allow users to specify which Git branch triggers production deployments. Previously, the system used a hardcoded default branch from the project configuration. Now users can select any available branch as their production branch through a new settings interface.

The deployment creation logic now automatically routes deployments to the production environment when deploying from the configured production branch, and to preview environments for all other branches.

Fixes #5469

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] Enhancement (small improvements)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How should this be tested?

- Navigate to project deployment settings and verify the new "Production branch" setting appears
- Test changing the production branch selection and saving the configuration
- Create deployments from the configured production branch and verify they deploy to production environment
- Create deployments from other branches and verify they deploy to preview environment
- Test the branch selection combobox with search functionality

### Required

- [ ] Filled out the "How to test" section in this PR
- [ ] Read [Contributing Guide](./CONTRIBUTING.md)
- [ ] Self-reviewed my own code
- [ ] Commented on my code in hard-to-understand areas
- [ ] Ran `pnpm build`
- [ ] Ran `pnpm fmt`
- [ ] Ran `make fmt` on `/go` directory
- [ ] Checked for warnings, there are none
- [ ] Removed all `console.logs`
- [ ] Merged the latest changes from main onto my branch with `git pull origin main`
- [ ] My changes don't cause any responsiveness issues

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Unkey Docs if changes were necessary

### CODE REVIEW

**Comment by Flo4604** [comment]
* **#5479** <a href="https://app.graphite.com/github/pr/unkeyed/unkey/5479?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.com/github/pr/unkeyed/unkey/5479?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: web/apps/dashboard/app/(app)/[workspaceSlug]/projects/[projectId]/(overview)/settings/components/build-settings/default-branch-settings.tsx [hunk 1]
```diff
@@ -0,0 +1,153 @@
...
+
+  const appId = data?.appId;
+  const repoConnection = data?.repoConnection;
+  const currentDefaultBranch = data?.defaultBranch ?? "main";
+
+  const [selectedBranch, setSelectedBranch] = useState<string | null>(null);
+
+  const repoFullName = repoConnection?.repositoryFullName;
+  const installationId = repoConnection?.installationId;
+  const [owner, repo] = repoFullName?.split("/") ?? [];
```
Comment (chronark) [inline web/apps/dashboard/app/(app)/[workspaceSlug]/projects/[projectId]/(overview)/settings/components/build-settings/default-branch-settings.tsx:28]: uuh does this blow up if the name is undefined?
idk what happens if you destructure an empty array

@ogzhanolguncu

Comment (ogzhanolguncu) [reply web/apps/dashboard/app/(app)/[workspaceSlug]/projects/[projectId]/(overview)/settings/components/build-settings/default-branch-settings.tsx:28]: naah good old JS will handle it 😄

Comment (Flo4604) [reply web/apps/dashboard/app/(app)/[workspaceSlug]/projects/[projectId]/(overview)/settings/components/build-settings/default-branch-settings.tsx:28]: lmfao
