### PR TITLE
fix: a user cannot click outside of the org selection modal

### LINKED ISSUE #4935: Clicking outside workspace picker shows org membership error
When switching between two accounts, clicking outside the “Select your workspace” modal can trigger an error like “user for pending authentication … does not belong to the organization …”. Ideally, clicking outside the modal should do nothing (or avoid showing this error).

[Clipboard-20260204-204134-028.mp4](https://uploads.linear.app/37afc8f2-981e-43da-b362-f19c2d9dcf01/9d50683a-f810-4f4d-ac89-b21b5697d43a/6c89389f-11e1-4961-997e-6308d12696aa?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzM3YWZjOGYyLTk4MWUtNDNkYS1iMzYyLWYxOWMyZDlkY2YwMS85ZDUwNjgzYS1mODEwLTRmNGQtYWM4OS1iMjFiNTY5N2Q0M2EvNmM4OTM4OWYtMTFlMS00OTYxLTk5N2UtNjMwOGQxMjY5NmFhIiwiaWF0IjoxNzcwMjM3Nzg4LCJleHAiOjE4MDE4MDgzNDh9.J1X-2WwZxKyb81CqdPnzXeHwGkXgpK8wtb_yqGbRB4w)

### PR DESCRIPTION
**Pull request by mcstepp**
## What does this PR do?

Fixes #4935 

Fix: Prevent org selector modal from closing when clicking outside the modal and improve auth error handling
Problem: Users could close the org selector modal during authentication, leading to:

- Stale pending session tokens causing "user does not belong to org" errors
- Confusing error messages when switching between different Google accounts
- Auth state mismatches when users closed the modal and signed in with a different account

### Changes
**Org Selector Modal**

- Made modal uncloseable from the outside by setting preventOutsideClose={true} 
- Users must now select an org to proceed, or close the modal to restart, or navigate back
- Removed unnecessary clientReady state that caused React hydration warnings

**Error Handling**

- Clear pending session cookie on org selection errors to prevent stale token issues
- Improved error message: "Your session has expired. Please sign in again." (consistent across all auth flows)
- Map WorkOS "does not belong to" errors to session expiration for better UX
- Use Next.js router instead of window.location.href to prevent TRPC errors during redirects

**Session Management**

- Pending session cookie is now deleted on both success and error in completeOrgSelection
- Session expiration check in sign-in page uses consistent error messaging
- Auto-redirect to sign-in after 1.5s when session expires

**Side Quests**
- Updated ESLint to not error in IDEs for unused vars prefixed with `_` (biome linter accepts this, and the build works, so this was more cosmetic annoyance for false positive than a hard failure)

Screenshot 2026-02-13 at 3 42 34 PM

Screenshot 2026-02-13 at 3 07 12 PM

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] Enhancement (small improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How should this be tested?

Prerequisites: A user with multiple workspaces

-  Modal cannot be closed by clicking outside or pressing ESC
-  X button is hidden
-  Switching Google accounts mid-flow shows proper error message
-  Session expiration redirects to sign-in with clear message
-  Successful org selection works as expected

### Required

- [x] Filled out the "How to test" section in this PR
- [x] Read [Contributing Guide](./CONTRIBUTING.md)
- [x] Self-reviewed my own code
- [x] Commented on my code in hard-to-understand areas
- [x] Ran `pnpm build`
- [x] Ran `pnpm fmt`
- [ ] Ran `make fmt` on `/go` directory
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues

### Appreciated

- [x] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Unkey Docs if changes were necessary

### CODE REVIEW

File: web/apps/dashboard/app/auth/sign-in/org-selector.tsx [hunk 1]
```diff
@@ -82,43 +91,21 @@ export const OrgSelector: React.FC<OrgSelectorProps> = ({ organizations, lastOrg
...
     },
-    [isLoading, setError],
+    [isLoading, setError, router],
   );
 
   const handleSubmit = useCallback(async () => {
     await submit(selectedOrgId);
   }, [submit, selectedOrgId]);
 
-  // Initialize org selector when client is ready
```
Comment (mcstepp) [inline web/apps/dashboard/app/auth/sign-in/org-selector.tsx:92]: Since this is a client component, the older stuff for hydration error prevention was no longer needed

File: web/apps/dashboard/app/auth/sign-in/org-selector.tsx [hunk 2]
```diff
@@ -133,8 +120,8 @@ export const OrgSelector: React.FC<OrgSelectorProps> = ({ organizations, lastOrg
             <div className="flex flex-col items-center gap-4 text-center">
               <h3 className="text-lg font-medium text-content">No workspaces found</h3>
               <p className="text-sm text-content-subtle max-w-md">
-                You don't have access to any workspaces. Please contact your administrator or create
-                a new workspace.
+                You don&apos;t have access to any workspaces. Please contact your administrator or
```
Comment (mcstepp) [inline web/apps/dashboard/app/auth/sign-in/org-selector.tsx:133]: something screamed about escaping apostrophes

File: web/apps/dashboard/app/auth/hooks/useSignIn.ts [hunk 3]
```diff
@@ -66,10 +66,19 @@ export function useSignIn() {
...
+              setOrgs([]);
+            }
           } catch (_err) {
-            setError("Failed to load organizations");
+            // Invalid JSON, clear orgs and don't show error
+            setOrgs([]);
           }
+        } else {
+          // No orgs param, clear orgs
+          setOrgs([]);
```
Comment (mcstepp) [inline web/apps/dashboard/app/auth/hooks/useSignIn.ts:81]: This block was to prevent invalid JSON token errors in the console

File: web/apps/dashboard/app/auth/sign-in/org-selector.tsx [hunk 4]
```diff
@@ -13,32 +14,30 @@ import {
...
-  useEffect(() => {
-    setClientReady(true);
-  }, []);
+  const router = useRouter();
+
+  const handleClose = useCallback(async () => {
+    // Clear pending auth state when user closes modal
+    await clearPendingAuth();
+    router.push("/auth/sign-in");
+  }, [router]);
```
[the remark this answers is not in the document]
Comment (mcstepp) [reply web/apps/dashboard/app/auth/sign-in/org-selector.tsx]: @coderabbitai review

File: web/apps/dashboard/app/auth/sign-in/[[...sign-in]]/page.tsx [hunk 5]
```diff
@@ -77,15 +82,31 @@ function SignInContent() {
...
+              // Ignore cookie deletion errors
+            });
+
             setError(result.message);
             setIsLoading(false);
             setIsAutoSelecting(false);
+
+            // If session expired, the pending auth was already cleared
+            // Just show the error and let user see org selector
+            if (result.code === AuthErrorCode.PENDING_SESSION_EXPIRED) {
```
Comment (chronark) [inline web/apps/dashboard/app/auth/sign-in/[[...sign-in]]/page.tsx]: this seems pointless, why are we doing an if check if we don't run any conditional code?

Comment (mcstepp) [reply web/apps/dashboard/app/auth/sign-in/[[...sign-in]]/page.tsx]: I was originally doing something with it, and it was an artifact from that, but I left to document behavior. Removing it.
